//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPVP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Displayresource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Displayresource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GPVP.Properties.Displayresource", typeof(Displayresource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPVP.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        internal static string DurationTag {
            get {
                return ResourceManager.GetString("DurationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePageName {
            get {
                return ResourceManager.GetString("HomePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        internal static string QualityTag {
            get {
                return ResourceManager.GetString("QualityTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags: .
        /// </summary>
        internal static string TagsTag {
            get {
                return ResourceManager.GetString("TagsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string TitleTag {
            get {
                return ResourceManager.GetString("TitleTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploader: .
        /// </summary>
        internal static string UploaderTag {
            get {
                return ResourceManager.GetString("UploaderTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        internal static string VersionTag {
            get {
                return ResourceManager.GetString("VersionTag", resourceCulture);
            }
        }
    }
}
